In [ ]:
#Linear Algebra

#Matrix? -> it is the rectanglular arrangement of anything which is in the form of rows and columns

#Rows- horizontal line of elements
#columns - vertical line of elements

#Matrix Dimension - if a matrix has m rows and the n columns -> dimension = m*n (rows * columns)

#Order of matrix -> no. of rows * no. of columns

#Matrix notation ? we should use the capital notations only (A,B,C,D)

#Real world examples ->
#1) data of the student marks -> student * subject
#2) sales data -> product * month * year
#3) hospital record -> patent * medical test


#Types of the matrix

#1) Row matrix -> the matrix which is having the row only
'''A = [10 20 30 40]
rows = 1, columns = 4, order => 1*4
# storing the marks of a single student


#2) Column matrix -> the matrix which is having the column only
A = [1
     2
     3
     4]
     no of rows => 4, no. of columns  = 1, order of the matrix = 4*1
     store the data of the temperature


#3) Rectangular Matrix -> in which the number of rows != number of columns
m != n
ex = student data
roll number, maths, hindi, english

#4) Square matrix => in which the number of rows = number of columns

#5) Zero matix / null matrix
in which the elements are zero
example -> A classroom where there is no test occured yet.


#6) Identity matrix / unit matrix
every diagonal element is 1
and rest every element is 0

A.I = A


#7) Diagonal Matrix -> a square matrix in which all the non-diagonal elements are zero

#7) Scalar Matrix -> a diagonal matrix in which all the diagonal elements are equal


#) every identity matrix is a scaler matrix
#) every scaler matrix is a diagonal matrix
#) every diagonal matrix is a square matrix


#) Upper triangular matrix -> all elements below the main diagonal are 0

#) Lower triangular matrix -> all elements above the diagonal are 0

#use case of upper and lower metrics are LU DECOMPOSTION, RANK OF THE MATRIX


#) Symmetric Matrix -> these are the type of the matix which are equal to their transpose




#) Matrix Operations



#) Break till 8:21





















In [ ]:
import numpy as np
a1 = np.array([[1,2,3],[5,6,7]])
print(a1)

[[1 2 3]
 [5 6 7]]


In [ ]:
#Operations On the matrix

m1 = np.array([[30,40,50],[10,15,30]])
m2 = np.array([[5,6,7],[8,9,10]])
print(m1)

[[30 40 50]
 [10 15 30]]


In [ ]:
print(m2)

[[5 6]
 [8 9]]


In [ ]:
#Addition->
#RULE -> Two matrics can be add iff they are having the same size

print(m1+m2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
print(m1-m2)

[[25 34 43]
 [ 2  6 20]]


In [ ]:
#Scaler Multiplication -> Multiplying a matrix by a single number
m2 = np.array([[100,200,300],[10,30,40]])
print(m2)

[[100 200 300]
 [ 10  30  40]]


In [ ]:
print(m2*2)

[[200 400 600]
 [ 20  60  80]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5],[6]])


In [ ]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5]
 [6]]


In [ ]:
print(np.dot(a,b))

[[17]
 [39]]


In [ ]:
#Transpose of the matix
m3 = np.array([[100,10,90,80],[40,50,60,70]])
print(m3)

[[100  10  90  80]
 [ 40  50  60  70]]


In [ ]:
m3.T

array([[100,  40],
       [ 10,  50],
       [ 90,  60],
       [ 80,  70]])

In [ ]:
#TRACE OF A MATRIX ??
 #Trace means the sum of the diagonal elements

m4 = np.array([[1,2],[3,4]])
print(m4)


m5 = np.array([[1,2],[3,4]])
print(m5)

NameError: name 'np' is not defined

In [ ]:
np.trace(m4)

np.int64(5)

In [ ]:
np.trace(m3)

NameError: name 'np' is not defined

In [ ]:
np.trace(m2)

NameError: name 'np' is not defined