In [ ]:
# Numpy -> Numerical Python
# Numpy -> it is powerful library
# numpy -> array, Nd array, multidimension array

In [ ]:
# List -> storing multiple values
# Disadvantages -->
# it takes a lot of time to execute because it stores actual memory adress of elements
# it consumes lots of memory
# we can't perform arithmetic operation directly in the list

In [ ]:
# Numpy array
# we can only have one datatype in an array [1,2,3,4.0,"sam"] -> [1.,2.,3.,4.0] -> float --- ["1","2","3","4.0"]
# it is very faster in comparison to list
# it provides lots of inbuild function for various arithmetic operation


In [ ]:
# how to create a numpy array--->

In [ ]:
import numpy as np # -> np is nickname/alias of numpy

In [ ]:
np_arr = np.array([1,2,3,4,5])
print(np_arr)

[1 2 3 4 5]


In [ ]:
print(type(np_arr)) # nd -> n-dim

<class 'numpy.ndarray'>


In [ ]:
np_array = np.array([[1,2,3],[4,5,6]])
print(np_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# datatype precedence in array
l = [1,2,3,4,6.8]
np_arr3 = np.array(l)
print(np_arr3)
np_arr3.dtype

[1.  2.  3.  4.  6.8]


dtype('float64')

In [ ]:
# float > int

In [ ]:
l = [1,2,3,4,6.8,"Sam"]
np_arr4 = np.array(l)
print(np_arr4)
np_arr4.dtype # U32 -> unicode string

['1' '2' '3' '4' '6.8' 'Sam']


dtype('<U32')

In [ ]:
# string > float > int

In [ ]:
# dtype -> datatype of elements of numpy array

**N Dimentions**

In [ ]:
# 0D -> 0 dimention
# it is scaler values means it is just a single point
zero_d = np.array(7)
print(zero_d)
print(type(zero_d))

7
<class 'numpy.ndarray'>


In [ ]:
# ndim -> number of dimension in an array

In [ ]:
print(zero_d.ndim)

0


In [ ]:
print(zero_d.shape)

()


In [ ]:
# 1-d array --> comnbination of multiple 0d elements

In [ ]:
one_d = np.array([1,2,3,4,5])
print(one_d)
print(type(one_d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
print(one_d.ndim)

1


In [ ]:
# shape
print(one_d.shape)

(5,)


In [ ]:
# 2d => combination of multiple 1d arrays
two_d = np.array([[1,2,3,5],[4,5,6,7],[4,5,6,7]])
print(two_d)

[[1 2 3 5]
 [4 5 6 7]
 [4 5 6 7]]


In [ ]:
print(two_d.ndim)

2


In [ ]:
print(two_d.shape)

(3, 4)


In [ ]:
# 3d => collection of multiple 2d arrays
three_d = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
print(three_d)

[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]


In [ ]:
print(three_d.ndim)

3


In [ ]:
print(three_d.shape)

(2, 2, 4)


**Indexing -->**

In [ ]:
one_d = np.array([1,2,3,4,5,6])
print(one_d)
print(one_d[5])

[1 2 3 4 5 6]
6


In [ ]:
two_d = np.array([[1,2,3,5],[4,5,6,7],[4,5,6,7]])
print(two_d)

[[1 2 3 5]
 [4 5 6 7]
 [4 5 6 7]]


In [ ]:
# [a,b] -> a = 1d array, b = 0d array
print(two_d[1,1])
print(two_d[2,3])

5
7


In [ ]:
three_d = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
print(three_d)

[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]


In [ ]:
# [a,b,c] -> a = 2d array, b = 1d array, c = 0d array
print(three_d[1,0,3])
print(three_d[1,1,1])

4
5


**Slicing -->**

In [ ]:
one_d = np.array([1,2,3,4,5,6])
print(one_d)
print(one_d[1:4])

[1 2 3 4 5 6]
[2 3 4]


In [ ]:
two_d = np.array([[1,2,3,5],[4,5,6,7],[4,5,6,7]])
print(two_d)

[[1 2 3 5]
 [4 5 6 7]
 [4 5 6 7]]


In [ ]:
print(two_d[0,1:3])  #same row, coloumn slicing

[2 3]


In [ ]:
print(two_d[0:2,1:4])

[[2 3 5]
 [5 6 7]]


In [ ]:
three_d = np.array([[[1,2,3,5],[4,5,6,7]],[[1,2,3,4],[10,20,30,40]]])
print(three_d)

[[[ 1  2  3  5]
  [ 4  5  6  7]]

 [[ 1  2  3  4]
  [10 20 30 40]]]


In [ ]:
print(three_d[0,0:2,1:3])

[[2 3]
 [5 6]]


In [ ]:
print(three_d[0:2,0:2,1:3])

[[[ 2  3]
  [ 5  6]]

 [[ 2  3]
  [20 30]]]


**Reshape--->**

In [ ]:
# it is just used to change the shape of array(changing the dimension)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr4 = arr.reshape(3,3)
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(8,)

In [ ]:
arr1 = arr.reshape(2,4)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr1 = arr.reshape(4,2)
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr = np.array([[1,23,4] ,[4,5,6],[7,8,9]])
arr

array([[ 1, 23,  4],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
arr1 = arr.reshape(9,1)
arr1

array([[ 1],
       [23],
       [ 4],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9]])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# MNIST dataset

In [ ]:
# converting this one-d array into 3-d
arr2 = arr.reshape(2,2,2)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# converting this one-d array into 3-d
arr2 = arr.reshape(4,2,1)
arr2

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[7],
        [8]]])

In [ ]:
# converting this one-d array into 3-d
arr2 = arr.reshape(2,1,4)
arr2

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [ ]:
# 2-d to 1-d
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1 = arr.reshape(9,)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# arr.reshape(2,2,-1)   -> 2*2*? = 8

**Methods to create numpyarray**

In [ ]:
# zeros()
# ones()
# full()
# arange()
# identity()
# eye()

In [ ]:
# np.zeros() -> it is used to create an array full of 0
arr = np.zeros(6,dtype = int)
arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
# np.zeros() -> it is used to create an array full of 0
arr = np.zeros((4,3),dtype = int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# np.ones() -> used to create an array full of 1
arr = np.ones((4,3),dtype = int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# np.full() -> shape,value, fill the entire array with value
arr = np.full((4,3),100)
arr

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [ ]:
# create an array in the given range
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(2,11,3)
arr

array([2, 5, 8])

In [ ]:
for i in range(2,11,3):
  print(i,end = " ")

2 5 8 

In [ ]:
# identity() -> creates a identity matrix
arr = np.identity(5,dtype = int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# np.identity => rows == coloumn
# np.eye => rows != coloumn
arr = np.eye(4,3,dtype = int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

**Random Module**

In [ ]:
# np.random.randint()
# randint() => random + int
x = np.random.randint(1,100)
x

89

In [ ]:
x = np.random.randint(1,100, size = 20)
x

array([10, 80, 90, 44, 35, 80, 91, 76, 91,  7, 23, 92, 71, 88, 38, 44, 51,
        9, 73, 35])

In [ ]:
#choice
dice = [1,2,3,4,5,6]
roll = np.random.choice(dice)
print(roll)

1


**Arithmetic Operation in Numpy**

In [ ]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l1 + l2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [ ]:
# mean -> average -> sum of all the elements/number of elements
arr = np.array([10,20,21,25,35,45])
arr

array([10, 20, 21, 25, 35, 45])

In [ ]:
ans = np.mean(arr)
print(ans)

26.0


In [ ]:
# median -> middle value
# median -> odd length -> 1 median
# even length -> 2 median => average of 2 median
arr = np.array([10,20,21,25,35,45,50])
ans = np.median(arr)
print(ans)

25.0


In [ ]:
#sort
arr = np.array([11,1,15,4,21,13])
arr_sorted = np.sort(arr)
arr_sorted

array([ 1,  4, 11, 13, 15, 21])

In [ ]:
#descending order
arr = np.array([11,1,15,4,21,13])
arr_sorted = np.sort(arr)[::-1]
arr_sorted

array([21, 15, 13, 11,  4,  1])

In [ ]:
import numpy as np
arr = np.array([10, 50, 5, 80, 25])
-10 -50-5-,25
3,1,4,.......
# Method 1: Negate the array before argsort
desc_idx = (-arr).argsort()
sorted_desc = arr[desc_idx]
print("Descending indices:", desc_idx) # [3 1 4 0 2]
print("Sorted descending:", sorted_desc) # [80 50 25 10 5]

https://drive.google.com/file/d/1eaifmLalJY2lcRSDqrYEi-j2bdi05k15/view?pli=1

In [ ]:
# That's all from my side thank You guys
# All the best for the next topics